title: FuzzyToast
description: Toast notifications for Windows Forms on .NET Framework 4.6.1+ and .NET 8+
baseurl: /FuzzyToast
markdown: kramdown
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
    values:
      layout: docs
